# -*- coding: utf-8 -*-
"""HW1 problem6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uBFcKkxrEBI0g38n5XzH6b3Ptv58uiw
"""

import random
import math
import matplotlib.pyplot as plt

random.seed(1145141919810)

exact_probability = 23 * math.pi / 192

sample_sizes = [10, 100, 1000, 10000, 100000, 1000000, 10000000]
estimates = []
count = 0
maximum_n = sample_sizes[-1]

for n in range(1, maximum_n + 1):
    x = random.random()
    y = random.random()
    z = random.random()
    if x * x + y * y < z and z * z > x * y:
        count = count + 1
    if n in sample_sizes:
        estimate = count / n
        estimates.append(estimate)
        print(
            "N =", n,
            "Estimate =", round(estimate, 4)
        )

print(
    "Analytic probability =",
    round(exact_probability, 4)
)

print(
    "Final difference =",
    round(estimates[-1] - exact_probability, 4)
)

plt.plot(
    sample_sizes,
    estimates,
    marker="o",
    label="Monte Carlo estimate"
)

plt.axhline(
    exact_probability,
    linestyle="--",
    label="Analytic value"
)

plt.xscale("log")
plt.xlabel("Sample size N")
plt.ylabel("Estimated probability")
plt.title("X, Y, Z are Uniform(0, 1)")
plt.legend()
plt.show()