# -*- coding: utf-8 -*-
"""HW2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnjLXKaLmGOAkkA00Gn2YlM0Ff0CMDW1
"""

import random
import math
import time
import matplotlib.pyplot as plt
#Problem3
N = 10000
width = 0.25

for rate in [0.5, 0.2]:
    random.seed(4560)
    c = 1 / (math.e * rate * (1 - rate))
    samples = []
    trials = 0

    start = time.perf_counter()
    while len(samples) < N:
        x = -math.log(1 - random.random()) / rate
        u = random.random()
        trials = trials + 1
        threshold = math.e * (1 - rate) * x * math.exp(-(1 - rate) * x)
        if u < threshold:
            samples.append(x)

    elapsed = time.perf_counter() - start

    print("rate =", rate)
    print("accepted =", len(samples), "proposals =", trials)
    print("c =", round(c, 6))
    print("empirical acceptance =", round(N / trials, 6))
    print("theoretical acceptance =", round(1 / c, 6))
    print("microseconds per accepted sample =", round(elapsed / N * 1000000, 4))
    print("sample mean =", round(sum(samples) / N, 6))
    print()

    upper = max(16, math.ceil(max(samples) / width) * width)
    bins = [i * width for i in range(round(upper / width) + 1)]
    grid = [i * upper / 1000 for i in range(1001)]
    theory = [x * math.exp(-x) for x in grid]

    plt.figure()
    plt.hist(samples, bins=bins, density=True, label="Simulation")
    plt.plot(grid, theory, label="Gamma(2, 1) PDF")
    plt.xlabel("x")
    plt.ylabel("Density")
    plt.title("Gamma(2, 1); proposal rate = " + str(rate) + "\nN = 10000; bin width = 0.25")
    plt.legend()
    plt.tight_layout()
    plt.close()

#Problem 4
a = 0.9
fast = 1000
slow = 10
width = 0.0005
samples = []
long_count = 0

N_4 = 10**5

for i in range(N_4):
    if random.random() < a:
        rate = fast
    else:
        rate = slow

    t = -math.log(1 - random.random()) / rate
    samples.append(t)
    if t > 0.05:
        long_count = long_count + 1

mean = sum(samples) / N_4
theory_mean = a / fast + (1 - a) / slow
theory_second = 2 * (a / fast**2 + (1 - a) / slow**2)
theory_variance = theory_second - theory_mean**2
theory_tail = a * math.exp(-fast * 0.05) + (1 - a) * math.exp(-slow * 0.05)

print("sample mean in seconds =", round(mean, 8))
print("theoretical mean in seconds =", round(theory_mean, 8))
print("sample P(T > 50 ms) =", round(long_count / N_4, 6))
print("theoretical P(T > 50 ms) =", round(theory_tail, 8))
print("theoretical variance in seconds squared =", round(theory_variance, 8))
print("theoretical CV =", round(math.sqrt(theory_variance) / theory_mean, 6))

upper = math.ceil(max(samples) / width) * width
bins = [i * width for i in range(round(upper / width) + 1)]
grid = [i * upper / 4000 for i in range(4001)]
theory = [a * fast * math.exp(-fast * t) + (1 - a) * slow * math.exp(-slow * t) for t in grid]

plt.figure()
plt.hist(samples, bins=bins, density=True, label="Composition samples")
plt.plot(grid, theory, label="Mixture PDF")
plt.yscale("log")
plt.xlim(0, upper)
plt.xlabel("Closed dwell time (s)")
plt.ylabel("Density (1/s)")
plt.title("a = 0.9; rates = 1000 and 10 per second\nN = 100000; bin width = 0.0005 s")
plt.legend()
plt.tight_layout()
plt.savefig("HW2_problem4.png", dpi=180)
plt.show()

import numpy as np
#Problem 5
u = np.random.random(100000)
direct_samples = 1 - np.sqrt(1 - u)

print("(b): direct sampling")
print("sample mean =", round(np.mean(direct_samples), 6))
print("theoretical mean =", round(1 / 3, 6))
print()

np.random.seed(1145141919)

R = 1000
C = np.ones(R, dtype=int)

for n in range(3, N):
    u = np.random.random(R)
    increase = u < C / n
    C = C + increase

z = C / N
mean = np.mean(z)
sd = np.std(z, ddof=1)

print("(c): growth process")
print("sample mean z =", round(mean, 6))
print("limiting theoretical mean z =", round(1 / 3, 6))
print("sample SD / mean =", round(sd / mean, 6))
print("limiting theoretical SD / mean =", round(1 / np.sqrt(2), 6))
print("sample mean C =", round(np.mean(C), 4))
print("smallest C =", np.min(C))
print("largest C =", np.max(C))

width = 0.05
bins = np.arange(0, 1.0001, width)
grid = np.linspace(0, 1, 201)

plt.figure()
plt.hist(z, bins=bins, density=True, label="Growth simulations")
plt.plot(grid, 2 * (1 - grid), label="Limiting PDF: 2(1-z)")
plt.xlabel("z = C / N")
plt.ylabel("Density")
plt.title("mu = 1; N = 10000; R = 1000\nBin width = 0.05")
plt.legend()
plt.tight_layout()
plt.show()