# -*- coding: utf-8 -*-
"""HW3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODTCxlv3B8ItAl9IXa295PM4Yrcqs55J
"""

import math
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1145141919)

R = 20000
T = 10000
d0 = 10
time = np.arange(T + 1)
curves = []
slopes = []

for N in [1, 2]:
    lamb = np.zeros(R, dtype=int)
    lions = np.full((N, R), d0, dtype=int)
    alive = np.ones(R, dtype=bool)
    survival = np.ones(T + 1)

    for t in range(1, T + 1):
        lamb = lamb + 2 * np.random.randint(0, 2, R) - 1
        lions = lions + 2 * np.random.randint(0, 2, (N, R)) - 1
        alive = alive & np.all(lions != lamb, axis=0)
        survival[t] = np.mean(alive)

    fit = (time >= 100) & (time <= 10000) & (survival > 0)
    slope, intercept = np.polyfit(np.log(time[fit]), np.log(survival[fit]), 1)
    curves.append(survival)
    slopes.append(slope)

    print("N =", N)
    print("slope =", round(slope, 6))
    print("beta =", round(-slope, 6))
    print("survivors at T =", np.sum(alive))
    print("zero survival points in fit window =", np.sum((time >= 100) & (survival == 0)))
    print()

S1 = curves[0]
S2 = curves[1]

print("t       S2(t)        S1(t)^2")
for t in [100, 1000, 10000]:
    print(t, "   ", round(S2[t], 8), "   ", round(S1[t] ** 2, 8))

positive_time = time[1:]
theory = [math.erf(d0 / (2 * math.sqrt(t))) for t in positive_time]

plt.figure()
keep = (time > 0) & (S1 > 0)
plt.loglog(time[keep], S1[keep], label="One lion: S1")
keep = (time > 0) & (S2 > 0)
plt.loglog(time[keep], S2[keep], label="Two lions: S2")
keep = (time > 0) & (S1 > 0)
plt.loglog(time[keep], S1[keep] ** 2, label="S1 squared")
plt.loglog(positive_time, theory, label="Continuum: erf(10 / (2 sqrt(t)))")
plt.xlabel("Time t (steps)")
plt.ylabel("Survival probability")
plt.title("R = 20000; T = 10000; d0 = 10; seed = 1145141919\n"
          + "Fit: 100 <= t <= 10000\n"
          + "Slopes: " + str(round(slopes[0], 4)) + ", " + str(round(slopes[1], 4))
          + "; beta: " + str(round(-slopes[0], 4)) + ", " + str(round(-slopes[1], 4)))
plt.legend()
plt.tight_layout()
plt.show()