# -*- coding: utf-8 -*-
"""HW4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10iRFruf8xFbYCzIa9vFHjOYeghaV7mL9
"""

import random
import numpy as np
import matplotlib.pyplot as plt

random.seed(1145141919810)

P = np.array([
    [0, 1/2, 1/2, 0, 0],
    [1/4, 0, 0, 1/2, 1/4],
    [3/4, 0, 0, 0, 1/4],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1]
])

starts = ["U", "I", "M"]
trials = 10000
all_times = []
all_fates = []
results = []

for start in range(3):
    times = []
    fates = []
    for run in range(trials):
        state = start
        t = 0
        while state < 3:
            u = random.random()
            cumulative = 0
            for j in range(5):
                cumulative = cumulative + P[state, j]
                if u < cumulative:
                    state = j
                    break
            t = t + 1
        times.append(t)
        fates.append(state)

    times = np.array(times)
    fates = np.array(fates)
    folded = times[fates == 3]
    aggregated = times[fates == 4]
    result = [len(folded)/trials, np.mean(times),
              np.mean(folded), np.mean(aggregated)]
    results.append(result)
    all_times.append(times)
    all_fates.append(fates)

exact = np.array([
    [1/2, 4, 4, 4],
    [5/8, 2, 9/5, 7/3],
    [3/8, 4, 5, 17/5]
])

lines = ["Seed = 1145141919810; 10000 independent chains per starting state.",
         "Start  h_hat    h       g_hat    g       tau_F_hat tau_F   tau_A_hat tau_A"]
for i in range(3):
    values = []
    for j in range(4):
        values.append("{:.4f} ({:.4f})".format(results[i][j], exact[i][j]))
    lines.append(starts[i] + "  " + "  ".join(values))
print("\n".join(lines))

Q = P[:3, :3]
R = P[:3, 3:]
times = all_times[1]
fates = all_fates[1]
maximum = int(max(times))
n = np.arange(1, maximum + 1)
bins = np.arange(0.5, maximum + 1.5, 1)

probability = np.array([0.0, 1.0, 0.0])
joint_pmf = []
for t in n:
    joint_pmf.append(probability @ R)
    probability = probability @ Q
joint_pmf = np.array(joint_pmf)

labels = ["folded", "aggregated"]
for j in range(2):
    selected = times[fates == j + 3]
    fate_probability = exact[1, 0] if j == 0 else 1 - exact[1, 0]
    conditional_pmf = joint_pmf[:, j] / fate_probability

    plt.figure()
    plt.hist(selected, bins=bins, density=True, label="Simulation")
    plt.plot(n, conditional_pmf, "o", label="Exact conditional PMF")
    plt.xlabel("Absorption time T (steps)")
    plt.ylabel("Probability (bin width = 1 step)")
    plt.title("Start I: " + labels[j] + " runs\n" + str(len(selected)) +
              " conditional samples; seed = 1145141919810")
    plt.xticks(np.arange(1, maximum + 1, 2))
    plt.legend()
    plt.tight_layout()
    plt.show()