# -*- coding: utf-8 -*-
"""HW5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173nFhulTKuK0-1_V14_ItT9bRrAIcCT-
"""

errors1 = np.max(np.abs(q2 - pi1), axis=1)

n = 0
while errors1[n] >= 1e-6:
    n = n + 1

values = np.linalg.eigvals(p2)
slem = np.sort(np.abs(values))[-2]

print('1(c)')
print('pi, linear solve =', pi1)
print('pi, binomial =', binomial)
print('maximum difference =', np.max(np.abs(pi1 - binomial)))
print('smallest n =', n)
print('error at n-1 =', errors1[n - 1])
print('error at n =', errors1[n])
print('eigenvalues =', np.sort(values)[::-1])
print('second largest eigenvalue modulus =', slem)
print()

plt.figure()
for k in range(5):
    plt.plot(range(151), q2[:, k], label='q_n(' + str(k) + ')')
plt.xlabel('n')
plt.ylabel('Probability')
plt.title('1(c): a = 0.3, b = 0.1; start = 0')
plt.legend()
plt.tight_layout()

p = np.array([
    [0, 1/2, 1/2, 0, 0, 0, 0, 0],
    [0, 0, 1/2, 1/2, 0, 0, 0, 0],
    [1/2, 0, 0, 0, 1/2, 0, 0, 0],
    [1/3, 0, 1/3, 0, 1/3, 0, 0, 0],
    [0, 1/3, 0, 0, 0, 1/3, 1/3, 0],
    [0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0]
])

q = np.ones(8) / 8

for n in range(100):
    q = q @ p

print('3(a)')
print('q100 =', q)
print('q101 =', q @ p)
print()

G = 0.85 * p + 0.15 / 8
pi = stationary(G)

q = np.ones(8) / 8
iterations = 0

while True:
    new_q = q @ G
    difference = np.sum(np.abs(new_q - q))
    q = new_q
    iterations = iterations + 1
    if difference < 1e-10:
        break

print('3(b)')
print('iterations =', iterations)
print('final update L1 difference =', difference)
print('pi, power iteration =', q)
print('pi, linear solve =', pi)
print('L1 difference between methods =', np.sum(np.abs(q - pi)))
print('ranking: 6 > 7 > 8 > 3 > 1 = 5 > 2 > 4')
print()

seed = 1145141919810
rng = np.random.default_rng(seed)
R = 100
T = 100000

x = np.zeros(R, dtype=int)
counts = np.zeros((R, 8), dtype=int)
rows = np.arange(R)

cdf = np.cumsum(G, axis=1)
cdf[:, -1] = 1

sizes = np.unique(np.logspace(2, 5, 61).astype(int))
errors = []
point = 0

for t in range(1, T + 1):
    u = rng.random(R)
    x = np.sum(u[:, None] >= cdf[x], axis=1)
    counts[rows, x] = counts[rows, x] + 1

    if point < len(sizes) and t == sizes[point]:
        estimates_now = counts / t
        maximum_errors = np.max(np.abs(estimates_now - pi), axis=1)
        errors.append(np.sqrt(np.mean(maximum_errors**2)))
        point = point + 1

estimates = counts / T
errors = np.array(errors)

slope, intercept = np.polyfit(np.log(sizes), np.log(errors), 1)
iid_se = np.sqrt(pi[5] * (1 - pi[5]) / T)

print('3(c)')
print('seed =', seed)
print('R =', R, '; T =', T, '; all starts = page 1')
print('Time averages use steps 1 through T, excluding time 0.')
print('surfer 1 estimate =', estimates[0])
print('mean estimate over 100 surfers =', np.mean(estimates, axis=0))
print('fitted slope =', slope)
print('RMS maximum error at T =', errors[-1])
print('IID page 6 standard error =', iid_se)
print('error / IID standard error =', errors[-1] / iid_se)
print()

pages = np.arange(1, 9)

plt.figure()
plt.bar(pages - 0.2, estimates[0], width=0.4, label='Surfer 1')
plt.bar(pages + 0.2, pi, width=0.4, label='Stationary distribution')
plt.xticks(pages)
plt.xlabel('Page')
plt.ylabel('Probability')
plt.title('3(c): T = 100000; seed = ' + str(seed))
plt.legend()
plt.tight_layout()

plt.figure()
plt.loglog(sizes, errors, label='RMS maximum error, R = 100')
plt.loglog(
    sizes,
    np.exp(intercept) * sizes**slope,
    label='Fitted slope = ' + str(round(slope, 4))
)
plt.xlabel('T')
plt.ylabel('RMS maximum error')
plt.title('3(c): discrete inverse-transform sampling')
plt.legend()
plt.tight_layout()

plt.show()